### ISSUE TITLE
About Singularity Scope

### ISSUE THREAD

**Issue by jennylsmith** [RSC-RP/nextflow_scri_config#1]
SCRI does have some recommended settings for Singularity in the nextflow config, but might not be correct for all pipelines. Here is an example of the singularity scope settings used in most SCRI pipelines. 

```
//Configs for singularity containers on cybertron
singularity {
    autoMounts = true
    cacheDir = "$HOME/singularity_test"
    runOptions = '--containall --no-home'
}
```

**Comment by ybaeus** [comment]
Added to README.md.
